### ISSUE TITLE
name in package.json

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/jquery-ajax-get-item#1]
"name": "ga-wdi-boston.browser-template",

**Comment by jrhorn424** [comment]
I believe the name is correct as of https://github.com/ga-wdi-boston/jquery-ajax-get-item/commit/95937e5d6f0226a1479b3942f33040cd456bc4f6 in `package.json`. Anyone care to confirm and close?

**Comment by danman01** [comment]
This is now correct. Closing.
