### ISSUE TITLE
require getFormFields

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/jquery-ajax-get-item#2]
This will get rid of a linter error and prepare us for: ga-wdi-boston/browser-template#49

**Comment by jrhorn424** [comment]
1f3410042e2dd3530a2a9a2a109e8c48648c3c57

**Comment by danman01** [comment]
This is present in the solution branch as @jrhorn424 mentioned in that commit link: https://github.com/ga-wdi-boston/jquery-ajax-get-item/blob/solution/assets/scripts/books/events.js#L5

Can we close this now or is there more needed?

**Comment by gaand** [comment]
@raq929 Can you comment?  What was your intent?  Did @jrhorn424 's  commit fulfill it?  Does the talk need scaffolding so whomever delivers it knows what to do?

**Comment by raq929** [comment]
Yes. We used to be including it in index.html or something strange. I don't remember what. Jeff's commit handles it.
