### ISSUE TITLE
Rename to jquery-ajax-get-element

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/jquery-ajax-get-item#3]
via @jrhorn424 and @gaand

**Comment by gaand** [comment]
Believe it.  We concurred in 015 planning. 🤖

**Comment by gaand** [comment]
Or not, I don't care that much.

**Comment by danman01** [comment]
Or `jquery-ajax-get-single`? I think 'item' works well too.

But, if it's not a concern, can we close this?

**Comment by gaand** [comment]
No, not that.  We both rejected `single`.

And no, do not close.  This should have been renamed.  Twice.  And now I care, a lot.

**Comment by danman01** [comment]
Made this change in f2618c8
When this PR gets merged, I will update the title of this repo and make issues on other repos in this sequence so that may point to the old name
